image: registry.gdut.edu.cn/docker/library/ubuntu:22.04

stages:
  - check
  - image-build
  - signing

cache:
  paths:
    - cache

sonarqube-check:
  image: 
    name: registry.gdut.edu.cn/docker/sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  stage: check
  tags:
    - dev
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  script: 
    - echo "========================== GENERATE VERSION TAGS ==========================="
    - export COMMIT_TIME=$(echo "$CI_COMMIT_TIMESTAMP" | tr -cd '0-9')
    - echo "The commit timestamp is $COMMIT_TIME"
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"
    - echo "============================ EXPORT IMAGE TAGS ============================="
    - echo "COMMIT_TIME=$COMMIT_TIME" >> build.env
  allow_failure: true
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 30 min
  only:
    - merge_requests
    - master
    - main
    - develop

docker-build-and-push:
  image: registry.gdut.edu.cn/docker/library/docker:stable
  stage: image-build
  tags:
    - Docker
  services:
    - name: docker:stable
  script:
    - echo "================================= LOAD ENV ================================="
    - env
    - echo "========================== GENERATE VERSION TAGS ==========================="
    - export COMMIT_TIME=$(echo "$CI_COMMIT_TIMESTAMP" | tr -cd '0-9')
    - echo "The commit timestamp is $COMMIT_TIME"
    - echo "============================= LOGIN TO HARBOR =============================="
    - docker login -u ${USERNAME} -p ${PASSWORD} ${HARBORHOST}
    - echo "=========================== BUILD DOCKER IMAGES ============================"
    - docker build -t ${HARBORHOST}/docker-registry-browser/docker-registry-browser:$(echo $COMMIT_TIME) .
    - echo "========================== TAG IMAGES WITH LATEST =========================="
    - docker tag ${HARBORHOST}/docker-registry-browser/docker-registry-browser:$(echo $COMMIT_TIME) ${HARBORHOST}/docker-registry-browser/docker-registry-browser:latest
    - echo "========================== PUSH IMAGES TO HARBOR ==========================="
    - docker push ${HARBORHOST}/docker-registry-browser/docker-registry-browser:$(echo $COMMIT_TIME)
    - docker push ${HARBORHOST}/docker-registry-browser/docker-registry-browser:latest
    - echo "============================= CLEAN UP MIRRORS ============================="
    - docker rmi ${HARBORHOST}/docker-registry-browser/docker-registry-browser:$(echo $COMMIT_TIME)
    - echo "============================ EXPORT IMAGE TAGS ============================="
    - echo "COMMIT_TIME=$COMMIT_TIME" >> build.env
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 30 min
  only:
    - master

helm-build:
  image: registry.gdut.edu.cn/docker/dtzar/helm-kubectl:3.8.0
  stage: image-build
  tags:
    - dev
  before_script:
    # 配置 Helm 和 Kubernetes
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - echo "$KUBECONFIG_DATA" | base64 -d > $KUBECONFIG
    - helm repo add stable https://charts.helm.sh/stable
    - helm repo update
  script:
    - echo "================================= LOAD ENV ================================="
    - env
    - echo "========================== GENERATE VERSION TAGS ==========================="
    - export COMMIT_TIME=$(echo "$CI_COMMIT_TIMESTAMP" | tr -cd '0-9')
    - echo "The commit timestamp is $COMMIT_TIME"
    - echo "============================= LOGIN TO HARBOR =============================="
    - helm registry login ${HARBORHOST} --username ${USERNAME} --password ${PASSWORD}
    - echo "============================== PACKAGE CHART ==============================="
    - helm package helm --version $(echo $COMMIT_TIME)
    - echo "=============================== PUSH CHARTS ================================"
    - helm push docker-registry-browser-helm* oci://${HARBORHOST}/docker-registry-browser
  artifacts:
    reports:
      dotenv: build.env
  only:
    - master


image-sign:
  image: registry.gdut.edu.cn/docker/library/ubuntu:22.04
  stage: signing
  tags:
    - dev
  before_script:
    - echo "============================ CHANGE APT MIRROR ============================="
    - echo 'deb http://mirrors.gdut.edu.cn/ubuntu/ jammy main restricted universe multiverse
      deb-src http://mirrors.gdut.edu.cn/ubuntu/ jammy main restricted universe multiverse
      deb http://mirrors.gdut.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse
      deb-src http://mirrors.gdut.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse
      deb http://mirrors.gdut.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse
      deb-src http://mirrors.gdut.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse
      deb http://mirrors.gdut.edu.cn/ubuntu/ jammy-security main restricted universe multiverse
      deb-src http://mirrors.gdut.edu.cn/ubuntu/ jammy-security main restricted universe multiverse' > /etc/apt/sources.list
    - apt update -y
    - echo "=============================== INSTALL CURL ==============================="
    - apt install curl -y
  script:
    - echo "================================= LOAD ENV ================================="
    - env
    - echo "COMMIT_TIME=${COMMIT_TIME}"
    - echo "============================== INSTALL COSIGN =============================="
    # - wget --no-check-certificate "https://cn-gz-1.minio.gdutnic.com/gdutnic/public/cosign_1.6.0_amd64.deb"
    - curl -fL -o cosign_1.6.0_amd64.deb --insecure "https://cn-gz-1.minio.gdutnic.com/gdutnic/public/cosign_1.6.0_amd64.deb"
    - dpkg -i cosign_1.6.0_amd64.deb
    - mv /usr/local/bin/cosign-linux-amd64 /usr/local/bin/cosign
    - echo "=============================== KEY GENERATE ==============================="
    - export COSIGN_PASSWORD=$PASSWORD
    - cosign generate-key-pair
    - echo "============================= LOGIN TO HARBOR =============================="
    - cosign login -u ${USERNAME} -p ${PASSWORD} ${HARBORHOST}
    - echo "=============================== IMAGE SIGN ================================="
    - cosign sign --key cosign.key ${HARBORHOST}/docker-registry-browser/docker-registry-browser:latest
    - echo "================================ CHART SIGN ================================"
    - cosign sign --key cosign.key $HARBORHOST/docker-registry-browser/docker-registry-browser-helm:$(echo $COMMIT_TIME)
    - echo "================================ EXPORT KEY ================================"
    - echo "The Password of the key is Harbor account's password, the key will reserved for 30 minutes."
    - echo "COMMIT_TIME=${COMMIT_TIME}" >> build.env
  artifacts:
    paths:
      - cosign.key
      - cosign.pub
    reports:
      dotenv: build.env
    expire_in: 30 min
  only:
    - master
