version: "3"

services:

  frontend:
    build: .
    environment:
      - "SECRET_KEY_BASE=changeme"
      - "HARBOR_URL=https://registry.gdut.edu.cn"
      - "HARBOR_USERNAME=robot$view-registry"
      - "HARBOR_PASSWORD=changeme"
      - "PUBLIC_REGISTRY_URL=https://registry.gdut.edu.cn"
      - "DOMAIN_MIRROR_MAP=ghcr.io:ghcr,quay.io:quay,registry.k8s.io:k8s,mcr.microsoft.com:mcr,gcr.io:gcr,docker.elastic.co:elastic,nvcr.io:nvcr,registry.gitlab.com:gitlab"
      - "NO_SSL_VERIFICATION=true"
    ports:
      - "8080:8080"
